name: Vertex Deployment

on:
  push:
    paths:
      - 'src/deploy/**'
      - 'src/label/**'

jobs:
  deploy-to-vertex-ai:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_NAME }} --password-stdin

      - name: Log in to GCP
        uses: google-github-actions/auth@v0
        with:
          credentials: ${{ secrets.GCP_KEY }}

      - name: Prepare GCP Key
        if: ${{ github.event_name == 'push' && (github.event.path | contains('src/deploy/') || github.event.path | contains('src/label/')) }}
        run: |
          echo -n "${{ secrets.GCP_KEY }}" | base64 --decode > gcp-key.json
          chmod 600 gcp-key.json

      - name: Build and push Docker image to Google Artifact Registry
        if: ${{ github.event_name == 'push' && (github.event.path | contains('src/deploy/') || github.event.path | contains('src/label/')) }}
        working-directory: src/deploy
        env:
          GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
        run: ./docker-push.sh

      - name: Update and Deploy model to Vertex AI endpoint
        if: ${{ github.event_name == 'push' && (github.event.path | contains('src/deploy/') || github.event.path | contains('src/label/')) }}
        env:
          GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
        run: |
          # Update the model in the Vertex AI Model Registry
          gcloud ai models versions create latest \
            --model=lnt-deploy-gpu \
            --region=us-central1 \
            --image=gcr.io/${GCP_PROJECT}/lus881/lnt-deploy-gpu:latest \
            --container-predict-route=/predict_sentiment \
            --container-health-route=/health

          # Deploy the updated model to the specified endpoint
          gcloud ai endpoints deploy lnt-endpoint-gpu \
            --region=us-central1 \
            --model=lnt-deploy-gpu

